'''
author: zyx
date: 2025-03-31
last modified: 2025-03-31
description: 
    Extract a mask from mask.npy files generated by cellpose gui segmentation
'''
import numpy as np
import argparse

def maskExtract(file_path:str,
                output_path:str):
    original_data = np.load(file_path, allow_pickle=True).item()
    np.save(output_path, original_data['masks'])
    print(f"Extracted mask saved to {output_path}")

def arguments_parser():
    parser = argparse.ArgumentParser(description='Extract mask from cellpose segmentation output')
    parser.add_argument('--file_path', type=str, required=True, help='Path to the mask.npy file')
    parser.add_argument('--output_path', type=str, required=True, help='Path to save the extracted mask')
    args = parser.parse_args()
    return args

if __name__ == "__main__":
    args = arguments_parser()
    maskExtract(file_path=args.file_path,
                output_path=args.output_path)